# Explicit CPU control of port/decks/grain_growth_2D_graintracker_fixed.i (P2 fixed-mesh first-light deck, derived from
# modules/phase_field/examples/grain_growth/grain_growth_2D_graintracker.i @ 6956830688).
# Changes vs the P2 deck (DESIGN section 8.5.1 + Q12): the GrainGrowth action expanded into explicit
# variables/kernels/material; [BCs/Periodic] REMOVED (constraints are silently ignored by the Kokkos assembly
# at the pin); hypre replaced by gamg with the assembled-matrix smoother (D-021); Campaign 01 instrumentation
# added (counters, PerfGraph sections; timing/memory postprocessors and solver counters written to CSV only).
# Mesh 176x176 (P2's 44x44 x uniform_refine 2), 100 grains, op_num 8, rand_seed 10, int_width 7, PJFNK
# block-diagonal, bdf2, IterationAdaptiveDT from dt=20, end_time 4000 (the tests spec overrides end_time=400).
# Generated by gen_decks.py: dim=2 n=176 L=1000 grains=100 op_num=8 backend=cpu track=prod pc=gamg-pmat
# Explicit expansion of the GrainGrowth action (DESIGN section 8.5); no periodic BCs (Q12).
# Physics: modules/phase_field/examples/grain_growth/grain_growth_2D_graintracker.i @ 6956830688 as in Campaign 01.

[Mesh]
  type = GeneratedMesh
  dim = 2
  nx = 176
  ny = 176
  xmax = 1000
  ymax = 1000
  elem_type = QUAD4
[]

[GlobalParams]
  op_num = 8
  var_name_base = gr
[]

[Variables]
  [gr0]
    order = FIRST
    family = LAGRANGE
  []
  [gr1]
    order = FIRST
    family = LAGRANGE
  []
  [gr2]
    order = FIRST
    family = LAGRANGE
  []
  [gr3]
    order = FIRST
    family = LAGRANGE
  []
  [gr4]
    order = FIRST
    family = LAGRANGE
  []
  [gr5]
    order = FIRST
    family = LAGRANGE
  []
  [gr6]
    order = FIRST
    family = LAGRANGE
  []
  [gr7]
    order = FIRST
    family = LAGRANGE
  []
[]

[UserObjects]
  [voronoi]
    type = PolycrystalVoronoi
    grain_num = 100
    rand_seed = 10
    int_width = 7
  []
[]

[ICs]
  [PolycrystalICs]
    [PolycrystalColoringIC]
      polycrystal_ic_uo = voronoi
    []
  []
[]

[AuxVariables]
  [bnds]
    order = FIRST
    family = LAGRANGE
  []
  [unique_grains]
    order = CONSTANT
    family = MONOMIAL
  []
  [var_indices]
    order = CONSTANT
    family = MONOMIAL
  []
[]

[AuxKernels]
  [bnds_calc]
    type = BndsCalcAux
    variable = bnds
    v = 'gr0 gr1 gr2 gr3 gr4 gr5 gr6 gr7'
    execute_on = 'initial timestep_end'
  []
  [unique_grains]
    type = FeatureFloodCountAux
    variable = unique_grains
    flood_counter = grains
    field_display = UNIQUE_REGION
    execute_on = 'initial timestep_end'
  []
  [var_indices]
    type = FeatureFloodCountAux
    variable = var_indices
    flood_counter = grains
    field_display = VARIABLE_COLORING
    execute_on = 'initial timestep_end'
  []
[]

[Kernels]
  [dt0]
    type = TimeDerivative
    variable = gr0
  []
  [bulk0]
    type = ACGrGrPoly
    variable = gr0
    v = 'gr1 gr2 gr3 gr4 gr5 gr6 gr7'
    mob_name = L
  []
  [int0]
    type = ACInterface
    variable = gr0
    mob_name = L
    kappa_name = kappa_op
    variable_L = true
  []
  [dt1]
    type = TimeDerivative
    variable = gr1
  []
  [bulk1]
    type = ACGrGrPoly
    variable = gr1
    v = 'gr0 gr2 gr3 gr4 gr5 gr6 gr7'
    mob_name = L
  []
  [int1]
    type = ACInterface
    variable = gr1
    mob_name = L
    kappa_name = kappa_op
    variable_L = true
  []
  [dt2]
    type = TimeDerivative
    variable = gr2
  []
  [bulk2]
    type = ACGrGrPoly
    variable = gr2
    v = 'gr0 gr1 gr3 gr4 gr5 gr6 gr7'
    mob_name = L
  []
  [int2]
    type = ACInterface
    variable = gr2
    mob_name = L
    kappa_name = kappa_op
    variable_L = true
  []
  [dt3]
    type = TimeDerivative
    variable = gr3
  []
  [bulk3]
    type = ACGrGrPoly
    variable = gr3
    v = 'gr0 gr1 gr2 gr4 gr5 gr6 gr7'
    mob_name = L
  []
  [int3]
    type = ACInterface
    variable = gr3
    mob_name = L
    kappa_name = kappa_op
    variable_L = true
  []
  [dt4]
    type = TimeDerivative
    variable = gr4
  []
  [bulk4]
    type = ACGrGrPoly
    variable = gr4
    v = 'gr0 gr1 gr2 gr3 gr5 gr6 gr7'
    mob_name = L
  []
  [int4]
    type = ACInterface
    variable = gr4
    mob_name = L
    kappa_name = kappa_op
    variable_L = true
  []
  [dt5]
    type = TimeDerivative
    variable = gr5
  []
  [bulk5]
    type = ACGrGrPoly
    variable = gr5
    v = 'gr0 gr1 gr2 gr3 gr4 gr6 gr7'
    mob_name = L
  []
  [int5]
    type = ACInterface
    variable = gr5
    mob_name = L
    kappa_name = kappa_op
    variable_L = true
  []
  [dt6]
    type = TimeDerivative
    variable = gr6
  []
  [bulk6]
    type = ACGrGrPoly
    variable = gr6
    v = 'gr0 gr1 gr2 gr3 gr4 gr5 gr7'
    mob_name = L
  []
  [int6]
    type = ACInterface
    variable = gr6
    mob_name = L
    kappa_name = kappa_op
    variable_L = true
  []
  [dt7]
    type = TimeDerivative
    variable = gr7
  []
  [bulk7]
    type = ACGrGrPoly
    variable = gr7
    v = 'gr0 gr1 gr2 gr3 gr4 gr5 gr6'
    mob_name = L
  []
  [int7]
    type = ACInterface
    variable = gr7
    mob_name = L
    kappa_name = kappa_op
    variable_L = true
  []
[]

[Materials]
  [CuGrGr]
    type = GBEvolution
    T = 450
    wGB = 14
    GBmob0 = 2.5e-6
    Q = 0.23
    GBenergy = 0.708
  []
[]

[Postprocessors]
  # --- correctness retention (cheap scalars) ---
  [dt]
    type = TimestepSize
  []
  [bnds_int]
    type = ElementIntegralVariablePostprocessor
    variable = bnds
  []
  [bnds_avg]
    type = ElementAverageValue
    variable = bnds
  []
  [gr0_max]
    type = NodalExtremeValue
    variable = gr0
    value_type = max
  []
  # --- counters ---
  [nl_its]
    type = NumNonlinearIterations
    outputs = 'csv'
  []
  [l_its]
    type = NumLinearIterations
    outputs = 'csv'
  []
  [res_evals]
    type = NumResidualEvaluations
    outputs = 'csv'
  []
  [failed_steps]
    type = NumFailedTimeSteps
    outputs = 'csv'
  []
  [n_dofs]
    type = NumDOFs
    system = NL
  []
  [n_elems]
    type = NumElements
  []
  [n_nodes]
    type = NumNodes
  []
  # --- memory (peak physical memory of the largest rank, MiB) ---
  [mem_max]
    type = MemoryUsage
    mem_type = physical_memory
    value_type = max_process
    report_peak_value = true
    execute_on = 'initial timestep_end'
    outputs = 'csv'
  []
  # --- PerfGraph sections: CUMULATIVE totals at each row (rank 0); analyze.py takes first differences.
  #     Timing/memory postprocessors and solver counters go to CSV only so Exodus holds physics and size
  #     identity (backend comparisons by exodiff); reduction order on a GPU can change iteration counts.
  [pg_root_total]
    type = PerfGraphData
    section_name = Root
    data_type = TOTAL
    must_exist = false
    outputs = 'csv'
  []
  [pg_solve_total]
    type = PerfGraphData
    section_name = 'FEProblem::solve'
    data_type = TOTAL
    must_exist = false
    outputs = 'csv'
  []
  [pg_res_total]
    type = PerfGraphData
    section_name = 'NonlinearSystemBase::computeResidualInternal'
    data_type = TOTAL
    must_exist = false
    outputs = 'csv'
  []
  [pg_res_calls]
    type = PerfGraphData
    section_name = 'NonlinearSystemBase::computeResidualInternal'
    data_type = CALLS
    must_exist = false
    outputs = 'csv'
  []
  [pg_jac_total]
    type = PerfGraphData
    section_name = 'NonlinearSystemBase::computeJacobianInternal'
    data_type = TOTAL
    must_exist = false
    outputs = 'csv'
  []
  [pg_jac_calls]
    type = PerfGraphData
    section_name = 'NonlinearSystemBase::computeJacobianInternal'
    data_type = CALLS
    must_exist = false
    outputs = 'csv'
  []
  [pg_gt_execute_total]
    type = PerfGraphData
    section_name = 'GrainTracker::execute'
    data_type = TOTAL
    must_exist = false
    outputs = 'csv'
  []
  [pg_gt_finalize_total]
    type = PerfGraphData
    section_name = 'GrainTracker::finalize'
    data_type = TOTAL
    must_exist = false
    outputs = 'csv'
  []
  [pg_gt_remap_total]
    type = PerfGraphData
    section_name = 'GrainTracker::remapGrains'
    data_type = TOTAL
    must_exist = false
    outputs = 'csv'
  []
  [pg_gt_remap_calls]
    type = PerfGraphData
    section_name = 'GrainTracker::remapGrains'
    data_type = CALLS
    must_exist = false
    outputs = 'csv'
  []
  [pg_csv_total]
    type = PerfGraphData
    section_name = 'CSV::outputStep'
    data_type = TOTAL
    must_exist = false
    outputs = 'csv'
  []
  [pg_console_total]
    type = PerfGraphData
    section_name = 'Console::outputStep'
    data_type = TOTAL
    must_exist = false
    outputs = 'csv'
  []
  [grains]
    type = GrainTracker
  []
[]

[Executioner]
  type = Transient
  scheme = bdf2
  solve_type = 'PJFNK'
  petsc_options_iname = '-pc_type -pc_use_amat -ksp_gmres_restart'
  petsc_options_value = 'gamg false 31'
  l_max_its = 50
  l_tol = 1e-4
  nl_max_its = 10
  start_time = 0.0
  end_time = 4000.0
  [TimeStepper]
    type = IterationAdaptiveDT
    dt = 20
    optimal_iterations = 6
  []
[]

[Preconditioning]
  # block-diagonal PJFNK as shipped (D-021 provisional port configuration); coupling-control runs
  # enable the full matrix from the command line: Preconditioning/active=smp
  active = ''
  [smp]
    type = SMP
    full = true
  []
[]

[Outputs]
  exodus = true
  csv = true
  perf_graph_json = true
  print_linear_residuals = false
[]
